# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  restapi:
    image: restapi
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7169:7169
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
