# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db: 
    image: restapi-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - 3308:3306
    networks:
      - udemy-network

  restapi:
    image: restapi
    build:
      context: .
      dockerfile: RestAPI/Dockerfile
    ports:
      - 7169:8080
      - 5257:8081
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
    networks:
      - udemy-network

networks:
  udemy-network: 
    driver: bridge


    